# Originally generated by ‘nixos-generate-config’.  Modify with care!
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-4cbc6029-cc46-40c0-aeee-f59f2effb5d2";
    fsType = "ext4";
  };
  boot.initrd.luks.devices."luks-4cbc6029-cc46-40c0-aeee-f59f2effb5d2".device =
    "/dev/disk/by-uuid/4cbc6029-cc46-40c0-aeee-f59f2effb5d2";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D072-A19A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/luks-c862bc1f-ecf7-42a9-8f78-4866ded9f041";
    fsType = "ext4";
  };
  boot.initrd.luks.devices."luks-c862bc1f-ecf7-42a9-8f78-4866ded9f041".device =
    "/dev/disk/by-uuid/c862bc1f-ecf7-42a9-8f78-4866ded9f041";

  # games partition
  fileSystems."/media/games" = {
    device = "/dev/mapper/luks-47a2ecc1-c33b-4ec2-9476-66671f412f77";
    fsType = "ext4";
  };
  #boot.initrd.luks.devices."luks-7a2127dc-2f95-4b4d-b38d-c0d60017bcac".device =
  boot.initrd.luks.devices."luks-47a2ecc1-c33b-4ec2-9476-66671f412f77".device =
    "/dev/disk/by-uuid/47a2ecc1-c33b-4ec2-9476-66671f412f77";

  # swap partition
  boot.initrd.luks.devices."aa3d21ed-9002-40fa-ad02-9c8dd556e8fe" = {
    device = "/dev/disk/by-uuid/aa3d21ed-9002-40fa-ad02-9c8dd556e8fe";
    # SSD optimisations
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  swapDevices = [
    {
      device = "/dev/mapper/aa3d21ed-9002-40fa-ad02-9c8dd556e8fe";
      randomEncryption.enable = true;
    }
  ];

  boot.resumeDevice = "/dev/mapper/aa3d21ed-9002-40fa-ad02-9c8dd556e8fe";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
